<a href="https://colab.research.google.com/github/themanoftalent/pyt-colab/blob/master/pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
df=pd.read_excel("TrainDataFeatures.xlsx")

In [ ]:
df.head()

,Unnamed: 0,lat,lon,Time,haversine_latlon_reallatlon,manhatten_latlon_reallatlon,bearing_latlon_reallatlon,centroid_long,centroid_lat,centroid_real_long,...,haversine_centlatlon_centreallatlon,haversine_latlon_centreallatlon,manhatten_latlon_centlatlon,manhatten_reallatlon_centreallatlon,manhatten_centlatlon_centreallatlon,bearing_latlon_centlatlon,bearing _reallatlon_centreallatlon,bearing _centlatlon_centreallatlon,speed_hvsn,speed_manhtn
0,1,41.042530,29.009342,25200,0.001068,0.001294,0.001661,29.019123,41.045799,29.019161,...,0.000000,0.793315,1.097296,0.967908,0.000000,0.122975,1.171496,0.000000,65.895939,61.369132
1,2,41.042532,29.009343,25261,0.003061,0.003677,0.000769,29.019123,41.045799,29.019161,...,0.000000,0.793655,1.073745,0.845202,0.000000,0.118068,1.377643,0.000000,74.770141,78.806212
2,3,41.042537,29.009344,25322,0.003029,0.004229,0.001442,29.019123,41.045799,29.019161,...,0.000000,0.777179,1.084039,0.961098,0.000000,0.125505,1.143219,0.000000,73.551324,80.690486
3,4,41.042544,29.009344,25383,0.003996,0.005408,0.000619,29.016040,41.044585,29.014983,...,0.291669,0.839080,0.133884,1.333816,0.393577,0.062255,1.390032,0.624139,56.911585,63.971747
4,5,41.042550,29.009340,25444,0.002881,0.003374,0.000791,29.019123,41.045799,29.019161,...,0.000000,0.793213,1.075087,0.846662,0.000000,0.118412,1.361577,0.000000,72.083388,84.411688

In [ ]:
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [ ]:
df.head()

,lat,lon,Time,haversine_latlon_reallatlon,manhatten_latlon_reallatlon,bearing_latlon_reallatlon,centroid_long,centroid_lat,centroid_real_long,centroid_real_lat,...,haversine_centlatlon_centreallatlon,haversine_latlon_centreallatlon,manhatten_latlon_centlatlon,manhatten_reallatlon_centreallatlon,manhatten_centlatlon_centreallatlon,bearing_latlon_centlatlon,bearing _reallatlon_centreallatlon,bearing _centlatlon_centreallatlon,speed_hvsn,speed_manhtn
0,41.042530,29.009342,25200,0.001068,0.001294,0.001661,29.019123,41.045799,29.019161,41.045820,...,0.000000,0.793315,1.097296,0.967908,0.000000,0.122975,1.171496,0.000000,65.895939,61.369132
1,41.042532,29.009343,25261,0.003061,0.003677,0.000769,29.019123,41.045799,29.019161,41.045820,...,0.000000,0.793655,1.073745,0.845202,0.000000,0.118068,1.377643,0.000000,74.770141,78.806212
2,41.042537,29.009344,25322,0.003029,0.004229,0.001442,29.019123,41.045799,29.019161,41.045820,...,0.000000,0.777179,1.084039,0.961098,0.000000,0.125505,1.143219,0.000000,73.551324,80.690486
3,41.042544,29.009344,25383,0.003996,0.005408,0.000619,29.016040,41.044585,29.014983,41.044191,...,0.291669,0.839080,0.133884,1.333816,0.393577,0.062255,1.390032,0.624139,56.911585,63.971747
4,41.042550,29.009340,25444,0.002881,0.003374,0.000791,29.019123,41.045799,29.019161,41.045820,...,0.000000,0.793213,1.075087,0.846662,0.000000,0.118412,1.361577,0.000000,72.083388,84.411688

In [ ]:
df.keys()

Index(['lat', 'lon', 'Time', 'haversine_latlon_reallatlon',
       'manhatten_latlon_reallatlon', 'bearing_latlon_reallatlon',
       'centroid_long', 'centroid_lat', 'centroid_real_long',
       'centroid_real_lat', 'haversine_latlon_centlatlon',
       'haversine_reallatlon_centreallatlon',
       'haversine_centlatlon_centreallatlon',
       'haversine_latlon_centreallatlon', 'manhatten_latlon_centlatlon',
       'manhatten_reallatlon_centreallatlon',
       'manhatten_centlatlon_centreallatlon', 'bearing_latlon_centlatlon',
       'bearing _reallatlon_centreallatlon',
       'bearing _centlatlon_centreallatlon', 'speed_hvsn', 'speed_manhtn'],
      dtype='object')

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
lat,1125.0,41.045583,0.000708,41.042530,41.045832,41.045835,41.045838,41.045841
lon,1125.0,29.018533,0.001956,29.009338,29.019198,29.019200,29.019203,29.019250
Time,1125.0,39817.438222,4551.345513,25200.000000,40149.000000,41125.000000,42101.000000,43199.000000
haversine_latlon_reallatlon,1125.0,0.089755,0.162089,0.000135,0.003029,0.004669,0.099040,0.618290
manhatten_latlon_reallatlon,1125.0,0.127059,0.223191,0.000161,0.003793,0.006421,0.177920,0.829750
bearing_latlon_reallatlon,1125.0,0.001243,0.001784,0.000005,0.000624,0.001154,0.001417,0.026069
centroid_long,1125.0,29.017899,0.002180,29.012924,29.016040,29.019123,29.019123,29.019123
centroid_lat,1125.0,41.045326,0.000839,41.043425,41.044585,41.045799,41.045799,41.045799
centroid_real_long,1125.0,29.017363,0.003363,29.010492,29.019161,29.019161,29.019161,29.019161
centroid_real_lat,1125.0,41.044671,0.001264,41.042854,41.042854,41.045820,41.045820,41.045820
haversine_latlon_centlatlon,1125.0,2.798612,3.746072,0.231175,0.768964,0.793109,3.727295,22.976168
haversine_reallatlon_centreallatlon,1125.0,1.422912,2.490372,0.109558,0.430581,0.693568,0.952773,20.861536
haversine_centlatlon_centreallatlon,1125.0,0.115328,0.205219,0.000000,0.000000,0.000000,0.291669,0.583001
haversine_latlon_centreallatlon,1125.0,4.763741,6.614756,0.355250,0.772177,0.793374,8.133103,28.768602
manhatten_latlon_centlatlon,1125.0,3.752059,5.056334,0.133884,1.061999,1.092849,5.065439,28.749949
manhatten_reallatlon_centreallatlon,1125.0,1.909027,3.290644,0.117310,0.541777,0.921484,1.341291,28.078318
manhatten_centlatlon_centreallatlon,1125.0,0.155252,0.276075,0.000000,0.000000,0.000000,0.393577,0.783796
bearing_latlon_centlatlon,1125.0,0.109732,0.023927,0.002471,0.110129,0.120861,0.122843,0.178144
bearing _reallatlon_centreallatlon,1125.0,1.093887,0.323457,0.042122,0.951351,1.189373,1.319526,1.776994
bearing _centlatlon_centreallatlon,1125.0,0.167840,0.277828,0.000000,0.000000,0.000000,0.624139,0.630762
speed_hvsn,1125.0,96.110344,377.484241,10.252213,68.322670,78.799883,94.501037,9022.408500
speed_manhtn,1125.0,3714.027837,5914.210791,4.058794,93.183737,156.311527,7089.834036,20761.392846

In [ ]:
df.isnull().sum()

lat                                    0
lon                                    0
Time                                   0
haversine_latlon_reallatlon            0
manhatten_latlon_reallatlon            0
bearing_latlon_reallatlon              0
centroid_long                          0
centroid_lat                           0
centroid_real_long                     0
centroid_real_lat                      0
haversine_latlon_centlatlon            0
haversine_reallatlon_centreallatlon    0
haversine_centlatlon_centreallatlon    0
haversine_latlon_centreallatlon        0
manhatten_latlon_centlatlon            0
manhatten_reallatlon_centreallatlon    0
manhatten_centlatlon_centreallatlon    0
bearing_latlon_centlatlon              0
bearing _reallatlon_centreallatlon     0
bearing _centlatlon_centreallatlon     0
speed_hvsn                             0
speed_manhtn                           0
dtype: int64

In [ ]:
df.shape

(1125, 22)

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
x = df.loc[:,].values
x = StandardScaler().fit_transform(x)

In [ ]:
np.mean(x),np.std(x)

(1.3084082863173022e-13, 1.0)

In [ ]:
feat_cols = ['ozellik'+str(i) for i in range(x.shape[1])]

In [ ]:
normalised_df = pd.DataFrame(x,columns=feat_cols)

In [ ]:
normalised_df.tail()

,ozellik0,ozellik1,ozellik2,ozellik3,ozellik4,ozellik5,ozellik6,ozellik7,ozellik8,ozellik9,...,ozellik12,ozellik13,ozellik14,ozellik15,ozellik16,ozellik17,ozellik18,ozellik19,ozellik20,ozellik21
1120,-1.144768,-1.056649,0.743311,-0.549064,-0.565581,0.275988,0.561614,0.564516,0.534834,-1.436979,...,-0.562226,-0.601060,-0.526163,-0.274977,-0.562604,0.559506,0.277568,-0.604382,-0.072679,-0.624765
1121,-1.176074,-1.086640,0.743311,-0.553149,-0.568812,-0.122188,0.561614,0.564516,-2.043531,-1.436979,...,-0.562226,-0.600345,-0.527477,-0.255080,-0.562604,0.437744,0.343750,-0.604382,-0.086686,-0.627576
1122,-1.205279,-1.114613,0.743311,-0.522286,-0.538348,-0.351248,-2.283391,-2.266485,0.534834,-1.436979,...,2.279909,0.872528,1.245606,-0.202702,2.277730,0.016599,0.918165,1.666960,-0.061699,2.312038
1123,-1.231402,-1.140405,0.743311,-0.526009,-0.541199,0.006664,0.561614,0.564516,0.534834,-1.436979,...,-0.562226,-0.601044,-0.525371,-0.439134,-0.562604,0.601421,0.398486,-0.604382,0.036932,-0.602299
1124,-1.255937,-1.163535,0.743311,-0.531447,-0.546817,-0.001917,0.561614,0.564516,0.534834,-0.379429,...,-0.562226,-0.600126,-0.523329,-0.397890,-0.562604,0.623350,0.489680,-0.604382,-0.021486,-0.607600

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca_df = PCA(n_components=17)

In [ ]:
principalComponents_df = pca_df.fit_transform(x)

In [ ]:
# col_cl= ['TemelBilAn'+str(i) for i in range(x.shape[1])]
# principal_df_Df = pd.DataFrame(data = principalComponents_df
#              , columns = ['Metin 1', 'Metin 2','Metin 3', 'Metin 4',
#                           'Metin 5', 'Metin 6','Metin 7',
#                           'Metin 8','Metin 9', 
#                           'Metin 10','Metin 11', 'Metin 12','Metin 13', 'Metin 14',
#                           'Metin 15', 'Metin 16','Metin 17'])

In [ ]:
col_cl= ['TMA_ '+str(i) for i in range(17)]

In [ ]:
principal_df_Df = pd.DataFrame(data = principalComponents_df
             , columns =col_cl)

In [ ]:
principal_df_Df.head()

,TMA_ 0,TMA_ 1,TMA_ 2,TMA_ 3,TMA_ 4,TMA_ 5,TMA_ 6,TMA_ 7,TMA_ 8,TMA_ 9,TMA_ 10,TMA_ 11,TMA_ 12,TMA_ 13,TMA_ 14,TMA_ 15,TMA_ 16
0,-2.257371,6.730758,0.660502,0.112510,0.577092,-0.110625,-1.454545,-1.106711,0.033386,-0.560203,-0.659128,-0.349606,-0.826769,-0.302251,-0.101564,0.026395,0.026632
1,-2.182123,6.632126,0.417324,0.489539,0.482085,-0.200806,-1.948421,-1.429481,0.149243,-0.242645,-0.599200,-0.334310,-0.830542,-0.301102,-0.107504,-0.005934,0.007708
2,-2.265608,6.677259,0.651616,0.068934,0.599258,-0.126301,-1.455063,-1.206689,-0.070865,-0.625874,-0.725884,-0.361561,-0.839049,-0.300315,-0.102420,0.020160,0.026293
3,0.680808,6.925692,0.211136,0.406114,-1.046167,-0.701736,-0.959140,-2.302882,0.710169,0.173019,2.054875,-0.094539,-0.989009,-0.743776,1.080648,-0.017541,0.087069
4,-2.186440,6.598216,0.428563,0.457447,0.484825,-0.197729,-1.921516,-1.415215,0.134548,-0.269547,-0.599818,-0.336731,-0.855135,-0.299002,-0.109311,-0.006782,0.012083